import json
import os

INPUT_FILE = os.path.join(os.path.dirname(__file__), "data", "dtc-codes.json")


def get_system(code, manufacturer):
    num = int(code[1:])
    if 1000 <= num <= 1199:
        return f"Sensores - {manufacturer} Enhanced"
    elif 1200 <= num <= 1399:
        return f"Combustível/Ignição - {manufacturer} Enhanced"
    elif 1400 <= num <= 1499:
        return f"Emissões - {manufacturer} Enhanced"
    elif 1500 <= num <= 1599:
        return f"Controle de Marcha Lenta - {manufacturer} Enhanced"
    elif 1600 <= num <= 1699:
        return f"ECU/PCM - {manufacturer} Enhanced"
    elif 1700 <= num <= 1799:
        return f"Transmissão - {manufacturer} Enhanced"
    return f"Motor (Powertrain) - {manufacturer} Enhanced"


def get_severity(code, desc):
    desc_lower = desc.lower()
    high_keywords = [
        "over temperature", "over-temperature", "protection active",
        "immobiliz", "theft", "shutdown", "crash", "disabled",
        "engine stall", "over pressure", "battery disconnect",
        "oil pressure too low", "coolant over", "rpm.*limiter",
        "forced engine shutdown", "mechanically failed",
    ]
    low_keywords = [
        "readiness", "not complete", "learning not complete",
        "snapshot", "data available", "reprogramm", "not programmed",
        "mileage not stored", "eeprom", "coding", "calibration",
        "idle learn", "adaptive clip", "monitor not enabled",
    ]
    for kw in high_keywords:
        if kw in desc_lower:
            return "high"
    for kw in low_keywords:
        if kw in desc_lower:
            return "low"
    return "medium"


def make_entry(code, desc_en, manufacturer):
    return {
        "code": code,
        "category": "P",
        "system": get_system(code, manufacturer),
        "description": desc_en,
        "description_en": desc_en,
        "description_pt": "",
        "severity": get_severity(code, desc_en),
    }


def build_oem_dtcs():
    entries = []

    # ==================== FORD ====================
    ford = {
        "P1000": "OBD Systems Readiness Test Not Complete",
        "P1100": "MAF Sensor Intermittent",
        "P1101": "MAF Sensor Out Of Self-Test Range",
        "P1112": "IAT Sensor Intermittent",
        "P1116": "ECT Sensor Out Of Self-Test Range",
        "P1117": "ECT Sensor Intermittent",
        "P1120": "TP Sensor Out Of Range Low",
        "P1121": "TP Sensor Inconsistent With MAF",
        "P1124": "TP Sensor Out Of Self-Test Range",
        "P1125": "TP Sensor Circuit Intermittent",
        "P1127": "Exhaust Not Warm Enough",
        "P1128": "Upstream O2 Sensors Swapped",
        "P1129": "Downstream O2 Sensors Swapped",
        "P1130": "Lack Of O2 Switch Bank 1",
        "P1131": "O2 Sensor Indicates Lean Bank 1",
        "P1132": "O2 Sensor Indicates Rich Bank 1",
        "P1150": "Lack Of O2 Switch Bank 2",
        "P1151": "O2 Sensor Indicates Lean Bank 2",
        "P1152": "O2 Sensor Indicates Rich Bank 2",
        "P1220": "Series Throttle Control Malfunction",
        "P1230": "Fuel Pump Low Speed Malfunction",
        "P1231": "Fuel Pump Secondary Circuit Low",
        "P1232": "Fuel Pump Speed Primary Circuit Malfunction",
        "P1233": "Fuel Pump Driver Module Offline",
        "P1234": "Fuel Pump Driver Module Disabled",
        "P1235": "Fuel Pump Control Out Of Range",
        "P1236": "Fuel Pump Control Out Of Range",
        "P1250": "PRC Solenoid Circuit Malfunction",
        "P1260": "THEFT Detected Vehicle Immobilized",
        "P1270": "Engine RPM Or Vehicle Speed Limiter Reached",
        "P1285": "Cylinder Head Over Temperature Condition",
        "P1299": "Cylinder Head Over Temperature Protection Active",
        "P1309": "Misfire Detection Monitor Not Enabled",
        "P1316": "Spark Plug Detection Module",
        "P1336": "Crankshaft Position Sensor Learning Not Complete",
        "P1340": "Camshaft Position Sensor B Circuit Malfunction",
        "P1345": "SGC Crankshaft/Camshaft Position Correlation",
        "P1350": "Ignition Diagnostic Monitor Malfunction",
        "P1351": "IDM Input Circuit Malfunction",
        "P1352": "Ignition Coil A Primary Circuit Malfunction",
        "P1353": "Ignition Coil B Primary Circuit Malfunction",
        "P1354": "Ignition Coil C Primary Circuit Malfunction",
        "P1355": "Ignition Coil D Primary Circuit Malfunction",
        "P1364": "Ignition Coil A Secondary Circuit Malfunction",
        "P1390": "Octane Adjust Pin Out Of Self-Test Range",
        "P1400": "DPFE Sensor Circuit Low",
        "P1401": "DPFE Sensor Circuit High",
        "P1405": "DPFE Sensor Upstream Hose Off Or Plugged",
        "P1406": "DPFE Sensor Downstream Hose Off Or Plugged",
        "P1407": "EGR No Flow Detected",
        "P1408": "EGR Flow Out Of Self-Test Range",
        "P1409": "EGR Vacuum Regulator Solenoid Circuit Malfunction",
        "P1411": "Secondary Air Injection System Incorrect Downstream Flow",
        "P1413": "Secondary Air Injection System Monitor Circuit Low",
        "P1414": "Secondary Air Injection System Monitor Circuit High",
        "P1442": "EVAP Control System Small Leak Detected",
        "P1443": "EVAP Control System Purge Control Valve Malfunction",
        "P1444": "EVAP Purge Flow Sensor Circuit Low",
        "P1445": "EVAP Purge Flow Sensor Circuit High",
        "P1449": "EVAP System Unable To Hold Vacuum",
        "P1450": "Unable To Bleed Up Fuel Tank Vacuum",
        "P1451": "EVAP Control System Canister Vent Solenoid Circuit Malfunction",
        "P1460": "Wide Open Throttle A/C Cut-Off Circuit Malfunction",
        "P1461": "A/C Pressure Sensor Circuit High",
        "P1462": "A/C Pressure Sensor Circuit Low",
        "P1463": "A/C Pressure Sensor Insufficient Pressure Change",
        "P1464": "A/C Demand Out Of Self-Test Range",
        "P1469": "Low A/C Cycling Period",
        "P1473": "Fan Secondary High With Fan Off",
        "P1474": "Low Fan Control Primary Circuit Malfunction",
        "P1500": "Vehicle Speed Sensor Intermittent",
        "P1501": "Vehicle Speed Sensor Out Of Self-Test Range",
        "P1502": "Vehicle Speed Sensor Intermittent Circuit Malfunction",
        "P1504": "Idle Air Control Circuit Malfunction",
        "P1505": "Idle Air Control System At Adaptive Clip",
        "P1506": "Idle Air Control Over Speed Error",
        "P1507": "Idle Air Control Under Speed Error",
        "P1516": "IMRC Input Error Bank 1",
        "P1517": "IMRC Input Error Bank 2",
        "P1518": "Intake Manifold Runner Control Stuck Open",
        "P1519": "Intake Manifold Runner Control Stuck Closed",
        "P1520": "Intake Manifold Runner Control Circuit Malfunction",
        "P1530": "A/C Clutch Circuit Malfunction",
        "P1537": "Intake Manifold Runner Control Stuck Open Bank 2",
        "P1538": "Intake Manifold Runner Control Stuck Closed Bank 2",
        "P1549": "Intake Manifold Communication Control Circuit Malfunction",
        "P1550": "Power Steering Pressure Sensor Malfunction",
        "P1565": "Speed Control Command Switch Out Of Range High",
        "P1566": "Speed Control Command Switch Out Of Range Low",
        "P1567": "Speed Control Output Circuit Continuity",
        "P1568": "Speed Control Unable To Hold Speed",
        "P1571": "Brake Switch Malfunction",
        "P1572": "Brake Pedal Position Sensor Circuit Malfunction",
        "P1573": "Throttle Position Not Available",
        "P1574": "Throttle Position Sensor Disagreement",
        "P1580": "Electronic Throttle Monitor PCM Override",
        "P1581": "Electronic Throttle Monitor Forced Engine Shutdown",
        "P1582": "Electronic Throttle Monitor Data Available",
        "P1583": "Electronic Throttle Monitor Cruise Disable",
        "P1584": "TCU Detected Electronic Throttle Malfunction",
        "P1585": "Throttle Control Unit Malfunction",
        "P1600": "PCM EEPROM Malfunction",
        "P1601": "ECM/PCM Serial Number Mismatch",
        "P1605": "PCM Keep Alive Memory Test Error",
        "P1625": "B+ Supply To VLCM Fan Circuit",
        "P1626": "B+ Supply To VLCM A/C Circuit",
        "P1627": "Module Supply Voltage Out Of Range",
        "P1628": "Module Ignition Supply Input Malfunction",
        "P1633": "KAM Voltage Too Low",
        "P1634": "Data Output Link Circuit Failure",
        "P1635": "Tire/Axle Ratio Out Of Acceptable Range",
        "P1636": "Inductive Signature Chip Communication Error",
        "P1639": "Vehicle ID Block Not Programmed",
        "P1640": "Powertrain DTCs Available In Another Module",
        "P1641": "Fuel Pump Primary Circuit Malfunction",
        "P1650": "Power Steering Pressure Switch Malfunction",
        "P1651": "Power Steering Pressure Switch Input Malfunction",
        "P1660": "Output Circuit Check Signal High",
        "P1661": "Output Circuit Check Signal Low",
        "P1670": "Electronic Feedback Signal Not Detected",
        "P1700": "Transmission Indeterminate Failure",
        "P1701": "Reverse Engagement Error",
        "P1703": "Brake Switch Out Of Self-Test Range",
        "P1705": "Transmission Range Sensor Out Of Self-Test Range",
        "P1709": "Park/Neutral Position Switch Out Of Self-Test Range",
        "P1711": "TFT Sensor Out Of Self-Test Range",
        "P1714": "Shift Solenoid A Inductive Signature Malfunction",
        "P1715": "Shift Solenoid B Inductive Signature Malfunction",
        "P1716": "Shift Solenoid C Inductive Signature Malfunction",
        "P1717": "Shift Solenoid D Inductive Signature Malfunction",
        "P1718": "TFT Sensor In Range Failure High",
        "P1727": "Coast Clutch Solenoid Inductive Signature Malfunction",
        "P1728": "Transmission Slip Error",
        "P1729": "4x4 Low Switch Error",
        "P1740": "Torque Converter Clutch Inductive Signature Malfunction",
        "P1741": "Torque Converter Clutch Control Error",
        "P1742": "Torque Converter Clutch Solenoid Mechanically Failed",
        "P1743": "Torque Converter Clutch Solenoid Mechanically Failed",
        "P1744": "Torque Converter Clutch System Performance",
        "P1746": "EPC Solenoid Circuit Low",
        "P1747": "EPC Solenoid Circuit High",
        "P1749": "EPC Solenoid Failed Low",
        "P1751": "Shift Solenoid A Performance",
        "P1754": "Coast Clutch Solenoid Circuit Malfunction",
        "P1756": "Shift Solenoid B Performance",
        "P1760": "EPC Solenoid Short Circuit",
        "P1761": "Shift Solenoid C Performance",
        "P1762": "Overdrive Band Failed Off",
        "P1765": "Timing Solenoid Performance",
        "P1767": "Torque Converter Clutch Circuit Malfunction",
        "P1775": "Transmission System MIL Malfunction",
        "P1779": "TCIL Circuit Malfunction",
        "P1780": "Transmission Control Switch Circuit Out Of Self-Test Range",
        "P1781": "4x4 Switch Out Of Self-Test Range",
        "P1783": "Transmission Over Temperature Condition",
        "P1785": "Transmission First And Reverse Gear Malfunction",
        "P1786": "3-2 Downshift Error",
        "P1787": "2-1 Downshift Error",
        "P1788": "Pressure Control Solenoid Open Circuit",
        "P1789": "Pressure Control Solenoid Short Circuit",
    }
    for code, desc in ford.items():
        entries.append(make_entry(code, desc, "Ford"))

    # ==================== GM ====================
    gm = {
        "P1031": "O2 Sensor Heater Current Monitor Control Circuit",
        "P1032": "O2 Sensor Heater Warm Up Control Circuit",
        "P1100": "MAF Sensor Intermittent",
        "P1105": "Secondary Vacuum Sensor Circuit",
        "P1106": "MAP Sensor Intermittent High Voltage",
        "P1107": "MAP Sensor Intermittent Low Voltage",
        "P1108": "BARO To MAP Comparison Too High",
        "P1111": "IAT Sensor Intermittent High",
        "P1112": "IAT Sensor Intermittent Low",
        "P1114": "ECT Sensor Intermittent Low",
        "P1115": "ECT Sensor Intermittent High",
        "P1120": "TP Sensor 1 Circuit",
        "P1121": "TP Sensor Intermittent High",
        "P1122": "TP Sensor Intermittent Low",
        "P1125": "APP System",
        "P1133": "O2 Sensor Insufficient Switching Bank 1",
        "P1134": "O2 Sensor Transition Time Ratio Bank 1",
        "P1153": "O2 Sensor Insufficient Switching Bank 2",
        "P1154": "O2 Sensor Transition Time Ratio Bank 2",
        "P1171": "Fuel System Lean During Acceleration",
        "P1174": "Fuel Trim Cylinder Balance Bank 1",
        "P1175": "Fuel Trim Cylinder Balance Bank 2",
        "P1187": "Fuel Tank Pressure Sensor Low",
        "P1188": "Fuel Tank Pressure Sensor High",
        "P1189": "Engine Oil Pressure Switch Circuit",
        "P1200": "Injector Control Circuit",
        "P1211": "Mass Airflow Sensor Performance",
        "P1214": "Injection Pump Timing Offset",
        "P1220": "TP Sensor 2 Circuit",
        "P1221": "TP Sensor 1-2 Correlation",
        "P1258": "Engine Coolant Over-Temperature Protection",
        "P1270": "A/C Refrigerant Over Pressure",
        "P1271": "A/C Low Side Temp Sensor High",
        "P1272": "A/C Low Side Temp Sensor Low",
        "P1273": "A/C High Side Temp Sensor High",
        "P1274": "A/C High Side Temp Sensor Low",
        "P1275": "Accelerator Pedal Position Sensor 1 Circuit",
        "P1276": "Accelerator Pedal Position Sensor 1 Performance",
        "P1280": "Accelerator Pedal Position Sensor 2 Circuit",
        "P1281": "Accelerator Pedal Position Sensor 2 Performance",
        "P1300": "Spark Timing Signal Not Sent",
        "P1305": "ICM Ignition Control Circuit High",
        "P1310": "ICM Ignition Control Circuit Low",
        "P1315": "ICM Ignition Control Circuit Intermittent",
        "P1320": "ICM 4X Ref Circuit Intermittent No Pulses",
        "P1321": "EI System IC Module 4X Ref Too Many Pulses",
        "P1322": "EI System IC Module 24X Ref Too Many Pulses",
        "P1323": "EI System IC Module 24X Ref Intermittent No Pulses",
        "P1336": "CKP System Variation Not Learned",
        "P1345": "Crankshaft Position Camshaft Position Correlation",
        "P1346": "Intake Camshaft Position Actuator Control Circuit",
        "P1350": "ICM Bypass Circuit High Voltage",
        "P1351": "ICM Ignition Control Circuit High Voltage",
        "P1361": "ICM Ignition Control Circuit Low Voltage",
        "P1374": "CKP Sensor 3X Reference Circuit High Resolution",
        "P1380": "Misfire Detected ABS Interaction Rough Road",
        "P1381": "Misfire Detected No Communication With EBCM",
        "P1390": "Wheel Speed Sensor 1 G-Sensor Intermittent",
        "P1400": "EGR Valve Pintle Position Sensor Circuit",
        "P1404": "EGR Valve Stuck Open",
        "P1405": "EGR Valve Stuck Closed",
        "P1406": "EGR Valve Pintle Position Circuit",
        "P1415": "Secondary Air Injection System Bank 1",
        "P1416": "Secondary Air Injection System Bank 2",
        "P1420": "Catalyst Temperature Sensor Circuit",
        "P1441": "EVAP System Flow During Non-Purge",
        "P1442": "EVAP System Leak Small",
        "P1450": "Barometric Pressure Sensor Circuit",
        "P1451": "Barometric Pressure Sensor Performance",
        "P1460": "Misfire Detected With Low Fuel Level",
        "P1480": "Cooling Fan 1 Control Circuit",
        "P1481": "Cooling Fan 2 Control Circuit",
        "P1482": "Cooling Fan 3 Control Circuit",
        "P1483": "Engine Cooling System Performance",
        "P1500": "Starter Signal Circuit",
        "P1501": "Vehicle Speed Sensor Intermittent",
        "P1502": "Theft Deterrent Signal",
        "P1508": "Idle Speed Low",
        "P1509": "Idle Speed High",
        "P1514": "Throttle Body Performance",
        "P1515": "Command Vs Actual Throttle Position",
        "P1516": "TAC Module Throttle Actuator Position Performance",
        "P1517": "TAC Module TP Performance",
        "P1518": "TAC Module Serial Data Malfunction",
        "P1519": "Throttle Actuator Control Module Serial Data",
        "P1520": "Park Neutral Position Switch Circuit",
        "P1521": "Transmission Engaged At High Throttle Angle",
        "P1523": "Throttle Return Spring Performance",
        "P1526": "TP Sensor Learned Closed Too High",
        "P1527": "Transmission Range Pressure Switch Comparison",
        "P1530": "Ignition Timing Adjustment Switch Circuit",
        "P1531": "A/C Refrigerant Pressure Sensor Circuit High",
        "P1532": "A/C Refrigerant Pressure Sensor Circuit Low",
        "P1539": "A/C Clutch Circuit High",
        "P1540": "A/C System High Pressure",
        "P1541": "A/C System Low Pressure",
        "P1545": "A/C Clutch Relay Control Circuit",
        "P1546": "A/C Refrigerant Condition Very Low",
        "P1554": "Cruise Control Status Circuit",
        "P1555": "EVO System Voltage High",
        "P1558": "Cruise Control Main Input High",
        "P1559": "Cruise Control Main Input Low",
        "P1560": "Cruise Control System Transaxle Not In Drive",
        "P1561": "Cruise Control System Brake Not Released",
        "P1562": "Cruise Control Servo Indicates Low",
        "P1564": "Cruise Control System Vehicle Accel Too High",
        "P1566": "Engine Cylinder 5 Misfire",
        "P1567": "Engine Cylinder 6 Misfire",
        "P1568": "Engine Cylinder 7 Misfire",
        "P1569": "Engine Cylinder 8 Misfire",
        "P1570": "Traction Control Active",
        "P1571": "Traction Control Torque Request",
        "P1572": "Traction Control System Active",
        "P1574": "Stop Lamp Switch System",
        "P1575": "Extended Travel Brake Switch Circuit",
        "P1579": "P/N to D/R at High Throttle Angle",
        "P1580": "Cruise Move Circuit Low",
        "P1581": "Cruise Move Circuit High",
        "P1582": "Cruise Direction Circuit Low",
        "P1583": "Cruise Direction Circuit High",
        "P1585": "Cruise Control Inhibit Output Circuit",
        "P1599": "Engine Stall Or Near Stall Detected",
        "P1600": "PCM Battery B+ Performance",
        "P1601": "PCM Serial Number Mismatch With VTD",
        "P1602": "PCM Loss Of Knock Retard Signal",
        "P1603": "PCM Loss Of SDM Serial Data",
        "P1604": "Loss Of IPC Serial Data",
        "P1605": "Diagnostic Lamp Driver Circuit",
        "P1610": "Loss Of EBCM DTC Data Serial Data",
        "P1611": "Loss Of CVRTD Serial Data",
        "P1614": "Loss Of VTD Message",
        "P1615": "VTD Fuel Disable",
        "P1617": "Engine Oil Level Switch Circuit",
        "P1619": "Engine Oil Life Monitor Reset Circuit",
        "P1620": "Low Engine Coolant Level",
        "P1621": "PCM Memory Performance",
        "P1622": "Cylinder Select Error",
        "P1623": "Transmission Temp Pull Up Resistor",
        "P1624": "Customer Snapshot Data Available",
        "P1625": "PCM Unexpected Reset",
        "P1626": "Theft Deterrent Fuel Enable Signal Not Received",
        "P1627": "A/D Performance",
        "P1628": "ECT Pull Up Resistor",
        "P1629": "Theft Deterrent Start Enable Not Received",
        "P1630": "Theft Deterrent Learn Mode Active",
        "P1631": "Theft Deterrent Start Enable Not Received",
        "P1632": "Theft Deterrent Fuel Disable Signal Received",
        "P1633": "Ignition Supplement Power Circuit Low",
        "P1634": "Ignition 1 Power Circuit Low",
        "P1635": "5 Volt Reference 1 Circuit",
        "P1636": "5 Volt Reference 2 Circuit",
        "P1637": "Generator L-Terminal Circuit",
        "P1638": "Generator F-Terminal Circuit",
        "P1639": "5 Volt Reference A Circuit",
        "P1640": "Output Driver Module A Fault",
        "P1641": "MIL Control Circuit",
        "P1642": "Vehicle Speed Output Circuit",
        "P1643": "Wait To Start Lamp Control Circuit",
        "P1644": "Traction Control Delivered Torque Output Circuit",
        "P1645": "EVAP Vent Solenoid Output Circuit",
        "P1646": "EVAP Vent Solenoid Output Circuit",
        "P1650": "Output Driver 2 Open/Short",
        "P1651": "Fan 1 Relay Control Circuit",
        "P1652": "Powertrain Induced Chassis Pitch Output Circuit",
        "P1653": "Oil Level Lamp Control Circuit",
        "P1654": "A/C Relay Control Circuit",
        "P1655": "EVAP Purge Solenoid Control Circuit",
        "P1656": "Wastegate Solenoid Control Circuit",
        "P1657": "Skip Shift Solenoid Control Circuit",
        "P1658": "A/C Clutch Feedback Circuit High",
        "P1660": "Cooling Fan Control Output Circuit",
        "P1661": "MIL Output Circuit",
        "P1662": "Cruise Inhibit Output Circuit",
        "P1663": "Oil Life Change Output Circuit",
        "P1664": "Skip Shift Lamp Control Circuit",
        "P1665": "EVAP Vent Solenoid Control",
        "P1666": "Injector Low Side Open",
        "P1667": "Reverse Inhibit Solenoid Control Circuit",
        "P1669": "ABS/TCS Output Circuit",
        "P1670": "Output Driver 4 Voltage High",
        "P1671": "MIL Circuit High",
        "P1672": "Low Engine Oil Level Lamp",
        "P1673": "Engine Hot Lamp Control Circuit",
        "P1674": "Tachometer Circuit",
        "P1675": "EVAP Vent Solenoid",
        "P1676": "EVAP Vent Solenoid",
        "P1680": "Output Driver 5 Circuit",
        "P1681": "Output Driver 6 Circuit",
        "P1682": "Output Driver 7 Circuit",
        "P1683": "Test Fault",
        "P1689": "Traction Control Delivered Torque",
        "P1690": "Crankshaft Reference Low Resolution",
        "P1700": "Transmission Component Slipping",
        "P1701": "Trans Fluid Sensor Performance",
        "P1703": "TCC Enable Solenoid Circuit Performance",
        "P1705": "P/N Signal Output Circuit",
        "P1709": "Park/Neutral Switch A Circuit Malfunction",
        "P1711": "TFP Valve Position Switch A/B Performance",
        "P1719": "Shift A/B Solenoid Performance",
        "P1720": "Vehicle Speed Sensor 2 Circuit",
        "P1727": "Transmission Ratio Error",
        "P1730": "2-3 Shift Solenoid Performance",
        "P1735": "1-2 Shift Not Commanded",
        "P1736": "2-3 Shift Not Commanded",
        "P1738": "High Gear Ratio Error",
        "P1739": "Transmission Slip",
        "P1740": "TCC Enable Solenoid Performance",
        "P1741": "TCC System Stuck Off",
        "P1742": "TCC System Stuck On",
        "P1743": "TCC Enable Solenoid Performance Stuck Off",
        "P1744": "TCC System Performance Engaged Too Long",
        "P1745": "Line Pressure Solenoid Performance",
        "P1760": "PCS 1 Circuit",
        "P1761": "2-3 Shift Solenoid Circuit Performance",
        "P1762": "Governor Pressure Sensor Offset Volts Too High Or Low",
        "P1763": "Governor Pressure Sensor Volts Too High",
        "P1764": "Governor Pressure Sensor Volts Too Low",
        "P1765": "Trans Line Pressure Solenoid A Performance",
        "P1770": "Clutch Solenoid Circuit",
        "P1773": "TCC Stator Temp Switch Circuit",
        "P1775": "Transmission System MIL Malfunction",
        "P1776": "Ignition Retard Request Circuit",
        "P1779": "Engine Torque Delivered To Trans Not Equal To Required Torque",
        "P1780": "PNP Switch Circuit",
        "P1781": "Engine Torque Signal Performance",
        "P1790": "Transmission Control Module Checksum",
        "P1791": "Transmission Control Module EEPROM",
        "P1792": "Transmission Control Module Reprogramming",
        "P1795": "Idle Learn Not Complete",
    }
    for code, desc in gm.items():
        entries.append(make_entry(code, desc, "GM"))

    # ==================== VW/Audi ====================
    vw = {
        "P1102": "O2 Sensor Heating Circuit Bank 1 Sensor 1 Short to B+",
        "P1105": "O2 Sensor Heating Circuit Bank 1 Sensor 2 Short to B+",
        "P1107": "O2 Sensor Heating Circuit Bank 2 Sensor 1 Short to B+",
        "P1110": "O2 Sensor Heating Circuit Bank 2 Sensor 2 Short to B+",
        "P1113": "Bank 1 Sensor 1 Internal Resistance Too High",
        "P1114": "Bank 1 Sensor 2 Internal Resistance Too High",
        "P1115": "O2 Sensor Heater Circuit Bank 1 Sensor 1 Short to Ground",
        "P1116": "O2 Sensor Heater Circuit Bank 1 Sensor 2 Short to Ground",
        "P1117": "O2 Sensor Heater Circuit Bank 2 Sensor 1 Short to Ground",
        "P1118": "O2 Sensor Heater Circuit Bank 2 Sensor 2 Short to Ground",
        "P1127": "Long Term Fuel Trim Add Air Bank 1 System Too Rich",
        "P1128": "Long Term Fuel Trim Add Air Bank 1 System Too Lean",
        "P1129": "Long Term Fuel Trim Add Air Bank 2 System Too Rich",
        "P1130": "Long Term Fuel Trim Add Air Bank 2 System Too Lean",
        "P1136": "Long Term Fuel Trim Add Fuel Bank 1 System Too Lean",
        "P1137": "Long Term Fuel Trim Add Fuel Bank 1 System Too Rich",
        "P1138": "Long Term Fuel Trim Add Fuel Bank 2 System Too Lean",
        "P1139": "Long Term Fuel Trim Add Fuel Bank 2 System Too Rich",
        "P1141": "Load Calculation Cross Check Range/Performance",
        "P1142": "Load Calculation Cross Check Lower Limit",
        "P1143": "Load Calculation Cross Check Upper Limit",
        "P1144": "Mass Air Flow Or Boost Pressure Incorrect",
        "P1145": "Intake Air Temp Sensor Short to Ground",
        "P1146": "Mass Air Flow Sensor Signal Too Low",
        "P1147": "Mass Air Flow Sensor Signal Too High",
        "P1148": "Mass Air Flow Sensor Power Supply Malfunction",
        "P1149": "Closed Loop Fuel Range Bank 2",
        "P1150": "Lack Of O2 Sensor Switching Sensor Before Cat Bank 2",
        "P1151": "Bank 2 Sensor 1 Long Term Fuel Trim Too Rich",
        "P1152": "Bank 2 Sensor 1 Long Term Fuel Trim Too Lean",
        "P1155": "Manifold Absolute Pressure Sensor Short to B+",
        "P1156": "Manifold Absolute Pressure Sensor Open/Short to Ground",
        "P1157": "Manifold Absolute Pressure Sensor Signal Too High",
        "P1158": "Manifold Absolute Pressure Sensor Signal Too Low",
        "P1160": "Manifold Air Temperature Sensor Short to B+",
        "P1161": "Manifold Air Temperature Sensor Open/Short to Ground",
        "P1162": "Fuel Temperature Sensor Short to B+",
        "P1163": "Fuel Temperature Sensor Open/Short to Ground",
        "P1164": "Fuel Temperature Sensor Signal Too High",
        "P1165": "Bank 1 Long Term Fuel Trim Range 1 Rich Limit",
        "P1166": "Bank 1 Long Term Fuel Trim Range 2 Rich Limit",
        "P1167": "Bank 2 Long Term Fuel Trim Range 1 Rich Limit",
        "P1168": "Bank 2 Long Term Fuel Trim Range 2 Rich Limit",
        "P1170": "Bank 1 Long Term Fuel Trim Range 1 Lean Limit",
        "P1171": "Throttle Actuation Potentiometer Sign 2 Range/Performance",
        "P1172": "Throttle Actuation Potentiometer Sign 2 Signal Too Low",
        "P1173": "Throttle Actuation Potentiometer Sign 2 Signal Too High",
        "P1176": "O2 Correction Behind Catalyst B1 Limit Attained",
        "P1177": "O2 Correction Behind Catalyst B2 Limit Attained",
        "P1178": "Linear O2 Sensor Circuit Bank 1 Sensor 1 No Activity",
        "P1179": "Linear O2 Sensor Circuit Bank 1 Sensor 2 No Activity",
        "P1180": "Automatic Trans Data Bus Missing",
        "P1181": "Cylinder 1 Misfire",
        "P1182": "Cylinder 2 Misfire",
        "P1183": "Cylinder 3 Misfire",
        "P1184": "Cylinder 4 Misfire",
        "P1185": "Cylinder 5 Misfire",
        "P1186": "Cylinder 6 Misfire",
        "P1196": "O2 Sensor Heater Circuit Bank 1 Sensor 1 Electrical Malfunction",
        "P1197": "O2 Sensor Heater Circuit Bank 2 Sensor 1 Electrical Malfunction",
        "P1198": "O2 Sensor Heater Circuit Bank 1 Sensor 2 Electrical Malfunction",
        "P1199": "O2 Sensor Heater Circuit Bank 2 Sensor 2 Electrical Malfunction",
        "P1201": "Cylinder 1 Fuel Injector Circuit Open/Short to B+",
        "P1202": "Cylinder 2 Fuel Injector Circuit Open/Short to B+",
        "P1203": "Cylinder 3 Fuel Injector Circuit Open/Short to B+",
        "P1204": "Cylinder 4 Fuel Injector Circuit Open/Short to B+",
        "P1205": "Cylinder 5 Fuel Injector Circuit Open/Short to B+",
        "P1206": "Cylinder 6 Fuel Injector Circuit Open/Short to B+",
        "P1213": "Cylinder 1 Fuel Injector Circuit Short to Ground",
        "P1214": "Cylinder 2 Fuel Injector Circuit Short to Ground",
        "P1215": "Cylinder 3 Fuel Injector Circuit Short to Ground",
        "P1216": "Cylinder 4 Fuel Injector Circuit Short to Ground",
        "P1217": "Cylinder 5 Fuel Injector Circuit Short to Ground",
        "P1218": "Cylinder 6 Fuel Injector Circuit Short to Ground",
        "P1225": "Cylinder 1 Fuel Injector Needle Lift Sensor Circuit",
        "P1226": "Cylinder 2 Fuel Injector Needle Lift Sensor Circuit",
        "P1227": "Cylinder 3 Fuel Injector Needle Lift Sensor Circuit",
        "P1228": "Cylinder 4 Fuel Injector Needle Lift Sensor Circuit",
        "P1237": "Cylinder 1 Fuel Injector Needle Lift Sensor Signal Too Low",
        "P1238": "Cylinder 2 Fuel Injector Needle Lift Sensor Signal Too Low",
        "P1239": "Cylinder 3 Fuel Injector Needle Lift Sensor Signal Too Low",
        "P1240": "Cylinder 4 Fuel Injector Needle Lift Sensor Signal Too Low",
        "P1250": "Fuel Level Sensor Signal Too Low",
        "P1251": "Fuel Level Sensor Signal Too High",
        "P1252": "Fuel Injection Pump Quantity Adjuster Malfunction",
        "P1253": "Fuel Injection Pump Quantity Adjuster Power Supply Low",
        "P1255": "Engine Coolant Temp Sensor Short to Ground",
        "P1256": "Engine Coolant Temp Sensor Open/Short to B+",
        "P1280": "Fuel Injection Air Control Valve Circuit Flow Too Low",
        "P1281": "Fuel Injection Air Control Valve Circuit Flow Too High",
        "P1282": "Fuel Injection Control Valve Circuit Electrical Malfunction",
        "P1283": "Fuel Injection Pump Fuel Metering Electromagnetic Valve",
        "P1284": "Fuel Injection Pump Fuel Metering Unit Error",
        "P1285": "Fuel Injection Pump Fuel Metering Excessive Tolerance",
        "P1286": "Fuel Injection Pump Control Module Short to B+",
        "P1287": "Fuel Injection Pump Control Module Short to Ground",
        "P1288": "Fuel Injection Pump Control Module Open Circuit",
        "P1289": "Turbocharger Recirculation Valve Short to B+",
        "P1290": "Turbocharger Recirculation Valve Open/Short to Ground",
        "P1295": "Turbocharger Bypass Valve Short to B+",
        "P1296": "Cooling System Malfunction",
        "P1297": "Connection Turbocharger-Throttle Valve Pressure Hose",
        "P1300": "Misfire Detected Reason Not Specified",
        "P1312": "Cylinder 2 Combustion Misfire",
        "P1313": "Cylinder 3 Combustion Misfire",
        "P1314": "Cylinder 4 Combustion Misfire",
        "P1319": "Knock Sensor 1 Signal Low",
        "P1320": "Knock Sensor 2 Signal Low",
        "P1321": "Knock Sensor 3 Signal Low",
        "P1322": "Knock Sensor 1 Signal Too High",
        "P1323": "Knock Sensor 2 Signal Too High",
        "P1324": "Knock Sensor 3 Signal Too High",
        "P1325": "Cylinder 1 Knock Control Limit Attained",
        "P1326": "Cylinder 2 Knock Control Limit Attained",
        "P1327": "Cylinder 3 Knock Control Limit Attained",
        "P1328": "Cylinder 4 Knock Control Limit Attained",
        "P1329": "Cylinder 5 Knock Control Limit Attained",
        "P1330": "Cylinder 6 Knock Control Limit Attained",
        "P1331": "Cylinder 1 Knock Control Test Pulse No Attenuation",
        "P1332": "Cylinder 2 Knock Control Test Pulse No Attenuation",
        "P1333": "Cylinder 3 Knock Control Test Pulse No Attenuation",
        "P1334": "Cylinder 4 Knock Control Test Pulse No Attenuation",
        "P1335": "Engine Torque Monitoring Adaptation",
        "P1336": "Engine Torque Monitoring Level 2",
        "P1337": "Camshaft Position Sensor Short to Ground",
        "P1338": "Camshaft Position Sensor Open/Short to B+",
        "P1339": "Crankshaft Position Sensor B+ Short",
        "P1340": "Crankshaft Position Sensor Ground Short",
        "P1341": "Ignition Coil Power Output Stage 1 Short to B+",
        "P1342": "Ignition Coil Power Output Stage 1 Short to Ground",
        "P1343": "Ignition Coil Power Output Stage 2 Short to B+",
        "P1344": "Ignition Coil Power Output Stage 2 Short to Ground",
        "P1345": "Ignition Coil Power Output Stage 3 Short to B+",
        "P1346": "Ignition Coil Power Output Stage 3 Short to Ground",
        "P1355": "Cylinder 1 Charge Time Short",
        "P1356": "Cylinder 2 Charge Time Short",
        "P1357": "Cylinder 3 Charge Time Short",
        "P1358": "Cylinder 4 Charge Time Short",
        "P1386": "Internal Control Module Knock Control Circuit",
        "P1387": "Internal Control Module Altitude Sensor Error",
        "P1388": "Internal Control Module Drive By Wire Error",
        "P1391": "Camshaft Position Sensor B Short to Ground",
        "P1392": "Camshaft Position Sensor B Open/Short to B+",
        "P1393": "Ignition Coil Power Output Stage 1 Open",
        "P1394": "Ignition Coil Power Output Stage 2 Open",
        "P1395": "Ignition Coil Power Output Stage 3 Open",
        "P1396": "Camshaft Position Sensor A Interruption",
        "P1400": "EGR Valve Circuit Electrical Malfunction",
        "P1401": "EGR Flow Sensor Open/Short to B+",
        "P1402": "EGR Valve Circuit Short to B+",
        "P1403": "EGR Valve Circuit Short to Ground",
        "P1404": "EGR Valve Circuit Open",
        "P1410": "Tank Ventilation Valve Short to B+",
        "P1420": "Secondary Air Injection Module Short to B+",
        "P1421": "Secondary Air Injection Module Short to Ground",
        "P1422": "Secondary Air Injection System Control Valve Circuit Short to B+",
        "P1423": "Secondary Air Injection System Control Valve Circuit Short to Ground",
        "P1424": "Secondary Air Injection System Control Valve Circuit Open",
        "P1425": "Tank Vent Valve Short to Ground",
        "P1426": "Tank Vent Valve Open",
        "P1432": "Secondary Air Injection Valve Open",
        "P1433": "Secondary Air Injection System Pump Relay Circuit Open",
        "P1434": "Secondary Air Injection System Pump Relay Circuit Short to B+",
        "P1435": "Secondary Air Injection System Pump Relay Circuit Short to Ground",
        "P1436": "Secondary Air Injection System Pump Relay Fuse",
        "P1450": "Secondary Air Injection System Circuit Short to B+",
        "P1451": "Secondary Air Injection System Circuit Short to Ground",
        "P1452": "Secondary Air Injection System Circuit Open",
        "P1471": "EVAP Emission Control LDP Circuit Short to B+",
        "P1472": "EVAP Emission Control LDP Circuit Short to Ground",
        "P1473": "EVAP Emission Control LDP Circuit Open",
        "P1475": "EVAP Emission Control LDP Malfunction",
        "P1476": "EVAP Emission Control LDP Insufficient Vacuum",
        "P1477": "EVAP Emission Control LDP Leak",
        "P1500": "Fuel Pump Relay Circuit Electrical Malfunction",
        "P1501": "Fuel Pump Relay Circuit Short to B+",
        "P1502": "Fuel Pump Relay Circuit Short to Ground",
        "P1505": "Closed Throttle Position Switch Does Not Close",
        "P1506": "Closed Throttle Position Switch Does Not Open",
        "P1507": "Idle System Learned Value Lower Limit",
        "P1508": "Idle System Learned Value Upper Limit",
        "P1512": "Intake Manifold Changeover Valve Circuit Short to B+",
        "P1515": "Intake Manifold Changeover Valve Circuit Short to Ground",
        "P1516": "Intake Manifold Changeover Valve Circuit Open",
        "P1519": "Intake Camshaft Control Bank 1 Malfunction",
        "P1522": "Intake Camshaft Control Bank 2 Malfunction",
        "P1525": "Camshaft Adjustment Bank 1 Malfunction",
        "P1529": "Camshaft Adjustment Bank 2 Malfunction",
        "P1530": "Camshaft Control Circuit Short to B+",
        "P1531": "Camshaft Control Circuit Short to Ground",
        "P1539": "Clutch Position Sensor Signal Too High",
        "P1540": "Vehicle Speed Signal Implausible",
        "P1541": "Fuel Pump Relay Circuit Open",
        "P1542": "Throttle Actuation Potentiometer Range/Performance",
        "P1543": "Throttle Actuation Potentiometer Signal Too Low",
        "P1544": "Throttle Actuation Potentiometer Signal Too High",
        "P1545": "Throttle Position Control Malfunction",
        "P1546": "Boost Pressure Control Valve Short to B+",
        "P1547": "Boost Pressure Control Valve Short to Ground",
        "P1548": "Boost Pressure Control Valve Open",
        "P1550": "Charge Pressure Deviation",
        "P1555": "Charge Pressure Upper Limit",
        "P1556": "Charge Pressure Negative Deviation",
        "P1557": "Charge Pressure Positive Deviation",
        "P1558": "Throttle Actuator Electrical Malfunction",
        "P1559": "Idle Speed Regulation Throttle Position Adaptation Malfunction",
        "P1560": "Maximum Engine Speed Exceeded",
        "P1564": "Idle Speed Control Throttle Position Lower Limit Not Attained",
        "P1565": "Idle Speed Control Throttle Position Upper Limit Exceeded",
        "P1580": "Electronic Power Control Malfunction",
        "P1582": "Idle Adaptation At Limit",
        "P1600": "Power Supply Terminal 30 Low Voltage",
        "P1602": "Power Supply Terminal 15 Low Voltage",
        "P1603": "Internal Control Module Malfunction",
        "P1604": "Internal Control Module Driver Error",
        "P1606": "Rough Road/Misfire Sensor Circuit Signal",
        "P1609": "Crash Shut-Off Activated",
        "P1610": "ECU Internal Error MIL Request",
        "P1611": "MIL Call-up Circuit Open",
        "P1612": "Electronic Control Module Incorrect Coding",
        "P1613": "MIL Call-up Circuit Short to B+",
        "P1614": "MIL Call-up Circuit Short to Ground",
        "P1616": "Glow Plug Indicator Lamp Circuit Short to B+",
        "P1617": "Glow Plug Indicator Lamp Circuit Short to Ground",
        "P1618": "Glow Plug Relay Circuit Short to B+",
        "P1619": "Glow Plug Relay Circuit Short to Ground",
        "P1620": "Coolant Temperature Gauge Circuit Short to B+",
        "P1621": "Coolant Temperature Gauge Circuit Short to Ground",
        "P1622": "Coolant Temperature Gauge Circuit Open",
        "P1624": "MIL Request Signal Active",
        "P1625": "CAN Data Bus Powertrain Missing Message From TCU",
        "P1626": "CAN Data Bus Powertrain Missing Message From EPC",
        "P1630": "Accelerator Pedal Position Sensor 1 Signal Too Low",
        "P1631": "Accelerator Pedal Position Sensor 1 Signal Too High",
        "P1632": "Accelerator Pedal Position Sensor 2 Signal Too Low",
        "P1633": "Accelerator Pedal Position Sensor 2 Signal Too High",
        "P1634": "Accelerator Pedal Position Sensor 3 Signal Too Low",
        "P1635": "Accelerator Pedal Position Sensor 3 Signal Too High",
        "P1636": "Accelerator Pedal Position Sensor 1 Power Supply Open/Short",
        "P1637": "Accelerator Pedal Position Sensor 2 Power Supply Open/Short",
        "P1639": "Accelerator Pedal Position Sensor 1-2 Range/Performance",
        "P1640": "Internal Control Module Function Error",
        "P1648": "Data Bus Powertrain Missing Message",
        "P1649": "Data Bus Powertrain Missing Message From ABS",
        "P1676": "Drive By Wire-MIL Circuit Open",
        "P1677": "Drive By Wire-MIL Circuit Short to B+",
        "P1690": "Malfunction Indication Lamp Malfunction",
        "P1691": "MIL Open Circuit",
        "P1692": "MIL Short to B+",
        "P1693": "MIL Short to Ground",
        "P1749": "Throttle Position Control Malfunction",
        "P1750": "Power Supply Voltage Out Of Range",
        "P1752": "Please Check DTC Memory Of Automatic Transmission",
        "P1762": "Brake Light Switch Range/Performance",
        "P1765": "Transmission Controlled Module Controller Area Network Error",
    }
    for code, desc in vw.items():
        entries.append(make_entry(code, desc, "VW/Audi"))

    # ==================== Toyota ====================
    toyota = {
        "P1100": "BARO Sensor Circuit",
        "P1120": "Accelerator Pedal Position Sensor Circuit",
        "P1121": "Accelerator Pedal Position Sensor Range/Performance",
        "P1125": "Throttle Control Motor Circuit",
        "P1126": "Magnetic Clutch Circuit",
        "P1127": "ETCS Actuator Power Source Circuit",
        "P1128": "Throttle Control Motor Lock",
        "P1129": "Electric Throttle Control System",
        "P1130": "Air Fuel Sensor Range/Performance Bank 1 Sensor 1",
        "P1133": "Air Fuel Sensor Circuit Response Bank 1 Sensor 1",
        "P1135": "Air Fuel Sensor Heater Circuit Response Bank 1 Sensor 1",
        "P1150": "Air Fuel Sensor Range/Performance Bank 1 Sensor 2",
        "P1153": "Air Fuel Sensor Circuit Response Bank 1 Sensor 2",
        "P1155": "Air Fuel Sensor Heater Circuit Response Bank 1 Sensor 2",
        "P1200": "Fuel Injector Circuit",
        "P1300": "Igniter Circuit Malfunction No 1",
        "P1305": "Igniter Circuit Malfunction No 2",
        "P1310": "Igniter Circuit Malfunction No 3",
        "P1315": "Igniter Circuit Malfunction No 4",
        "P1320": "Igniter Circuit Malfunction No 5",
        "P1325": "Igniter Circuit Malfunction No 6",
        "P1330": "Igniter Circuit Malfunction No 7",
        "P1335": "Crankshaft Position Sensor Circuit",
        "P1340": "Igniter Circuit Malfunction No 8",
        "P1346": "VVT Sensor/Camshaft Position Range/Performance Bank 1",
        "P1349": "VVT System Malfunction",
        "P1400": "Sub-Throttle Position Sensor",
        "P1401": "Sub-Throttle Position Sensor Performance",
        "P1405": "Turbo Pressure Sensor Circuit",
        "P1410": "EGR Valve Position Sensor Circuit Malfunction",
        "P1411": "EGR Valve Position Sensor Performance",
        "P1420": "EGR Valve Function",
        "P1436": "Purge Flow Sensor Circuit",
        "P1437": "Purge Flow Sensor Range/Performance",
        "P1440": "EVAP System Vacuum Switch",
        "P1441": "Vacuum Cut Valve Bypass Valve Malfunction",
        "P1442": "EVAP Vacuum Switch Circuit",
        "P1443": "EVAP Control System Vent Valve",
        "P1445": "EVAP System Purge Volume Control Valve",
        "P1446": "EVAP Control System Vent Circuit",
        "P1447": "EVAP System Vent Control Valve",
        "P1448": "EVAP System Switching Valve Control",
        "P1449": "EVAP System Vent System",
        "P1450": "EVAP System Small Leak",
        "P1451": "EVAP Canister System",
        "P1500": "Starter Signal Circuit",
        "P1510": "Air Volume Too Low With ETC Fully Open",
        "P1511": "Throttle Control Motor Circuit Intermittent",
        "P1512": "Throttle Position Sensor 1 Intermittent",
        "P1513": "Throttle Position Sensor 2 Intermittent",
        "P1515": "Throttle Motor Current Sensor Circuit",
        "P1516": "Throttle Motor Position Sensor Circuit",
        "P1517": "Throttle Motor Position Sensor Range/Performance",
        "P1518": "Throttle Motor Locked Rotor",
        "P1519": "Idle Speed Control Valve Closing Coil",
        "P1520": "Stop Light Switch Signal",
        "P1521": "A/C Compressor Speed Sensor Circuit",
        "P1523": "Cruise Control Switch Circuit",
        "P1525": "A/C Pressure Sensor Circuit",
        "P1530": "A/C Compressor Signal Circuit",
        "P1565": "Cruise Main Switch Circuit",
        "P1566": "Cruise Control Main Switch Circuit Low",
        "P1600": "ECM Battery Malfunction",
        "P1603": "ECM Communication Circuit",
        "P1604": "Startability Malfunction",
        "P1605": "Knock Control CPU Malfunction",
        "P1607": "Cruise Control Input Processor",
        "P1610": "ECU Check Engine Problem",
        "P1615": "ECU Identification Not Registered",
        "P1616": "ECM GND Circuit",
        "P1618": "SDM Signal Circuit",
        "P1620": "Engine Coolant Temp Sensor Signal High Circuit 2",
        "P1621": "Engine Coolant Temp Sensor Signal Low Circuit 2",
        "P1625": "ECM Matching",
        "P1630": "Traction Control System Malfunction",
        "P1631": "Traction Control Throttle Input Signal",
        "P1632": "Traction Control System Main Switch Input Signal",
        "P1633": "ECM Communication Circuit",
        "P1634": "ECM Voltage Problem",
        "P1635": "5-Volt Reference Circuit A High",
        "P1636": "5-Volt Reference Circuit A Low",
        "P1645": "Body Control Module Signal",
        "P1650": "EFI Relay Malfunction",
        "P1656": "OCV Circuit Bank 1",
        "P1658": "OCV Circuit Bank 2",
        "P1661": "Valve Timing Control Open Bank 1",
        "P1662": "Valve Timing Control Short Bank 1",
        "P1663": "Valve Timing Control Open Bank 2",
        "P1664": "Valve Timing Control Short Bank 2",
        "P1665": "VVTL Oil Pressure Switch Circuit Bank 1",
        "P1666": "VVTL Oil Pressure Switch Circuit Bank 2",
        "P1690": "OCV Malfunction Bank 1",
        "P1692": "OCV Malfunction Bank 2",
        "P1693": "Variable Valve Timing Over-Advanced Bank 1",
        "P1694": "Variable Valve Timing Over-Retarded Bank 1",
        "P1700": "Vehicle Speed Sensor Circuit Malfunction",
        "P1705": "Direct Clutch Speed Sensor Circuit Malfunction",
        "P1710": "AT Speed Sensor Circuit Malfunction",
        "P1715": "Number 3 Speed Sensor Circuit Malfunction",
        "P1720": "AT Turbine Speed Sensor Circuit Malfunction",
        "P1725": "AT Speed Sensor Circuit Intermittent",
        "P1730": "AT Gear Ratio Abnormal",
        "P1735": "AT Fluid Temperature Sensor Circuit High",
        "P1740": "AT Fluid Temperature Sensor Circuit Low",
        "P1745": "AT Control System Malfunction",
        "P1750": "AT System Lock Up Clutch",
        "P1755": "AT Solenoid 1 Malfunction",
        "P1760": "AT Solenoid 2 Malfunction",
        "P1765": "Linear Shift Solenoid Circuit",
        "P1770": "Linear Shift Solenoid Performance",
        "P1775": "Linear Shift Solenoid Circuit Low",
        "P1780": "Park/Neutral Position Switch Malfunction",
    }
    for code, desc in toyota.items():
        entries.append(make_entry(code, desc, "Toyota"))

    # ==================== Honda ====================
    honda = {
        "P1106": "BARO Pressure Sensor Range/Performance",
        "P1107": "BARO Pressure Sensor Circuit Low",
        "P1108": "BARO Pressure Sensor Circuit High",
        "P1128": "MAP Sensor Signal Lower Than Expected",
        "P1129": "MAP Sensor Signal Higher Than Expected",
        "P1149": "Primary O2 Sensor Range/Performance Bank 1",
        "P1157": "Primary O2 Sensor Circuit Low Bank 2",
        "P1158": "Primary O2 Sensor Circuit High Bank 2",
        "P1162": "Primary O2 Sensor Circuit Slow Response Bank 2",
        "P1163": "Primary O2 Sensor Slow Response Bank 2",
        "P1166": "Primary O2 Sensor Heater Circuit Bank 2",
        "P1167": "Primary O2 Sensor Heater Circuit Bank 2 Failure",
        "P1253": "VTEC System Malfunction Bank 1",
        "P1259": "VTEC System Malfunction Bank 2",
        "P1279": "VTEC System Malfunction Solenoid Valve",
        "P1280": "VTEC Pressure Switch Circuit Low",
        "P1281": "VTEC Pressure Switch Circuit High",
        "P1297": "ELD Circuit Low Voltage",
        "P1298": "ELD Circuit High Voltage",
        "P1300": "Random Misfire",
        "P1316": "Spark Plug Detect Bank 1",
        "P1317": "Spark Plug Detect Bank 2",
        "P1336": "CKP Sensor Intermittent Interruption",
        "P1337": "CKP Sensor No Signal",
        "P1359": "CKP/TDC Sensor Connector Disconnection",
        "P1361": "TDC Sensor Intermittent Interruption",
        "P1362": "TDC Sensor No Signal",
        "P1366": "TDC/CKP Sensor Connector Disconnection",
        "P1381": "Camshaft Position Sensor Intermittent Interruption",
        "P1382": "Camshaft Position Sensor No Signal",
        "P1399": "Random Misfire",
        "P1401": "EGR Valve Lift Sensor Circuit High",
        "P1404": "EGR Valve Pintle Position Circuit Range",
        "P1406": "EGR Valve Pintle Position Sensor Circuit Malfunction",
        "P1456": "EVAP Control System Leak Detected Fuel Tank",
        "P1457": "EVAP Control System Leak Detected Canister",
        "P1459": "EVAP Purge Flow Switch Malfunction",
        "P1486": "Thermostat Range/Performance Problem",
        "P1491": "EGR Valve Lift Insufficient Detected",
        "P1498": "EGR Valve Lift Sensor High Voltage",
        "P1508": "IAC Valve Circuit",
        "P1509": "IAC Valve Circuit",
        "P1519": "Idle Air Control Valve Circuit",
        "P1607": "PCM Internal Circuit A",
        "P1655": "TMA Or TMB Signal Line Error",
        "P1656": "Module Output Error",
        "P1660": "A/T FI Signal A Low",
        "P1671": "A/T FI Signal A High",
        "P1672": "A/T FI Signal B Low",
        "P1673": "A/T FI Signal B High",
        "P1676": "FI Signal 1",
        "P1677": "FI Signal 2",
        "P1678": "FPTDR Signal A Low",
        "P1679": "FPTDR Signal A High",
        "P1681": "A/T FI Signal A Circuit",
        "P1682": "A/T FI Signal B Circuit",
        "P1684": "A/T Throttle Position Input Error",
        "P1686": "A/T Serial Communication Error",
        "P1690": "A/T System Gear Selection Problem",
        "P1705": "A/T Gear Position Switch Short",
        "P1706": "A/T Gear Position Switch Open",
        "P1709": "A/T Mode Switch Circuit",
        "P1738": "A/T 2nd Pressure Switch",
        "P1739": "A/T 3rd Pressure Switch",
        "P1740": "A/T 4th Pressure Switch",
        "P1750": "A/T System Mechanical Problem",
        "P1751": "A/T Mainshaft Speed Sensor Intermittent Interruption",
        "P1753": "A/T Lockup Clutch Pressure Switch Circuit",
        "P1758": "A/T Clutch Pressure Control Solenoid A",
        "P1768": "A/T Clutch Pressure Control Solenoid B",
        "P1773": "A/T Clutch Pressure Control Solenoid C",
        "P1785": "A/T D4 Indicator Switch Circuit Malfunction",
        "P1786": "A/T D5 Indicator Switch Circuit Malfunction",
        "P1790": "A/T Throttle Position Output Line",
        "P1791": "A/T Vehicle Speed Output Line",
        "P1792": "A/T IDM Signal Line",
        "P1793": "A/T ECT Signal Line",
        "P1794": "A/T Brake Signal Line",
        "P1795": "A/T D4 Switch Signal Circuit",
    }
    for code, desc in honda.items():
        entries.append(make_entry(code, desc, "Honda"))

    # ==================== Fiat/Stellantis ====================
    fiat = {
        "P1100": "MAP/BARO Sensor Switch Solenoid",
        "P1105": "Fuel Pressure Solenoid Circuit",
        "P1110": "General Throttle Position",
        "P1115": "General Engine Temp Error",
        "P1121": "TP Sensor A/D Circuit",
        "P1128": "Closed Loop Fueling Not Achieved Bank 1",
        "P1129": "Closed Loop Fueling Not Achieved Bank 2",
        "P1187": "Oil Pressure Condition",
        "P1188": "Engine Oil Temperature",
        "P1189": "Engine Oil Pressure Too Low",
        "P1193": "Inlet Air Temp Sensor High",
        "P1194": "Inlet Air Temp Sensor Low",
        "P1195": "Fuel Sender 1 Circuit",
        "P1196": "Fuel Sender 2 Circuit",
        "P1197": "Alternator Target Not Reached",
        "P1198": "Radiator Temp Sensor High",
        "P1199": "Radiator Temp Sensor Low",
        "P1281": "Engine Is Cold Too Long",
        "P1282": "Fuel Pump Relay Control Circuit",
        "P1283": "Idle Select Signal Invalid",
        "P1284": "Fuel Injection Timing Offset",
        "P1285": "Fuel Injection Pump Controller Power Supply",
        "P1286": "Accelerator Position Sensor Supply Above Normal",
        "P1287": "Fuel Injection Pump Controller Short to B+",
        "P1288": "Intake Manifold Short Runner Solenoid",
        "P1289": "Manifold Tune Valve Solenoid",
        "P1290": "CNG Fuel System Pressure Too High",
        "P1291": "Fuel Injection Timing Intermittent",
        "P1292": "CNG Pressure Sensor Voltage Too High",
        "P1293": "CNG Pressure Sensor Voltage Too Low",
        "P1294": "Target Idle Not Reached",
        "P1295": "No 5 Volt Supply to TP Sensor",
        "P1296": "MAP Sensor Pressure Too Low",
        "P1297": "MAP Sensor Pressure Too High",
        "P1298": "Lean Operation At Wide Open Throttle",
        "P1299": "Vacuum Leak Found IAC Fully Seated",
        "P1300": "Spark Timing Signal Not Sent",
        "P1388": "Auto Shutdown Relay Circuit",
        "P1389": "Auto Shutdown Relay Circuit No Voltage",
        "P1390": "Timing Belt Skipped One Tooth or More",
        "P1391": "Intermittent Loss Of CKP Or CMP",
        "P1398": "Misfire Adaptive Numerator At Limit",
        "P1399": "Wait To Start Lamp Circuit",
        "P1400": "Battery Temperature Sensor Performance",
        "P1401": "EGR System Performance",
        "P1403": "EGR Circuit Short to B+",
        "P1404": "EGR Open Position Performance",
        "P1478": "Battery Temperature Out Of Range",
        "P1480": "PCV Solenoid Circuit",
        "P1486": "EVAP Leak Monitor Pinched Hose Found",
        "P1489": "High Speed Radiator Fan Relay Circuit",
        "P1490": "Low Speed Radiator Fan Relay Circuit",
        "P1491": "Radiator Fan Control Relay Circuit",
        "P1492": "Ambient/Battery Temperature Sensor High",
        "P1493": "Ambient/Battery Temperature Sensor Low",
        "P1494": "EVAP Leak Detection Pump Pressure Switch",
        "P1495": "EVAP Leak Detection Pump Solenoid Circuit",
        "P1496": "EVAP Leak Detection Pump Insufficient Vacuum",
        "P1498": "Auxiliary 5 Volt Supply Output Too Low",
        "P1499": "Hydraulic Fan Solenoid Failure",
        "P1500": "Generator Lamp Circuit Malfunction",
        "P1501": "Generator Set Field Circuit",
        "P1502": "Generator Voltage Sense Out Of Range",
        "P1594": "Charging System Voltage Too High",
        "P1595": "Speed Control Solenoid Circuit",
        "P1596": "Speed Control Switch Always High",
        "P1597": "Speed Control Switch Always Low",
        "P1598": "A/C Pressure Sensor Circuit High",
        "P1599": "A/C Pressure Sensor Circuit Low",
        "P1600": "PCM A/D Converter Error",
        "P1602": "PCM Not Programmed",
        "P1603": "PCM Internal Dual Port RAM Communication Failure",
        "P1604": "PCM Internal Dual Port RAM Read Failure",
        "P1607": "PCM Internal Shutdown Timer Rationality",
        "P1618": "SCI Receive Error",
        "P1680": "Clutch Released Switch Circuit",
        "P1681": "No I/P Cluster CCD/Bus Messages",
        "P1682": "Charging System Voltage Too Low",
        "P1683": "Speed Control Power Relay Driver Circuit",
        "P1684": "Battery Disconnected Within Last 50 Starts",
        "P1685": "Smart Key Invalid",
        "P1686": "No SKIM Bus Messages",
        "P1687": "No Communication With MIC",
        "P1688": "Internal Fuel Injection Pump Controller",
        "P1689": "No Communication with Body Control Module",
        "P1690": "Fuel Injection Pump CKP Signal Fault",
        "P1691": "Fuel Injection Pump Controller Calibration Error",
        "P1692": "Fault In Companion Module",
        "P1693": "DTC Stored In Companion Module",
        "P1694": "No CCD/Bus Message From Companion Module",
        "P1695": "No CCD/Bus Message From BCM",
        "P1696": "PCM EEPROM Write Denied",
        "P1697": "PCM EMR Mileage Not Stored",
        "P1698": "No CCD/Bus Message From TCM",
        "P1699": "No CCD/Bus Message From PCM",
        "P1740": "TCC Or Overdrive Solenoid Performance",
        "P1756": "Governor Pressure Not Equal To Target At 15-20 PSI",
        "P1757": "Governor Pressure Above 3 PSI In Gear With 0 MPH",
        "P1762": "Governor Pressure Sensor Offset Volts Too Low Or Too High",
        "P1763": "Governor Pressure Sensor Volts Too High",
        "P1764": "Governor Pressure Sensor Volts Too Low",
        "P1765": "Trans 12 Volt Supply Relay Control Circuit",
        "P1775": "Solenoid Switch Valve Latched In TCC Position",
        "P1776": "Solenoid Switch Valve Latched In LR Position",
        "P1790": "Fault Immediately After Shift",
        "P1791": "Battery Was Disconnected",
        "P1793": "TRD Link Communication Error",
        "P1794": "Speed Sensor Ground Error",
    }
    for code, desc in fiat.items():
        entries.append(make_entry(code, desc, "Fiat/Stellantis"))

    # ==================== Hyundai/Kia ====================
    hyundai = {
        "P1110": "Intake Air Temperature Sensor Open/Short",
        "P1111": "Intake Air Temperature Sensor Performance",
        "P1114": "Ambient Air Temperature Sensor Open",
        "P1115": "Ambient Air Temperature Sensor Short",
        "P1116": "Engine Coolant Temperature Sensor Performance",
        "P1117": "Engine Coolant Temperature Sensor Open",
        "P1118": "Engine Coolant Temperature Sensor Short",
        "P1121": "Throttle Position Sensor A Signal Low",
        "P1122": "Throttle Position Sensor A Signal High",
        "P1123": "Throttle Position Sensor B Signal Low",
        "P1124": "Throttle Position Sensor B Signal High",
        "P1126": "Throttle Position Sensor A-B Correlation",
        "P1127": "Throttle Position Sensor C Signal Low",
        "P1128": "Throttle Position Sensor C Signal High",
        "P1140": "Load Calculation Error",
        "P1145": "Intake Manifold Swirl Control Open",
        "P1146": "Intake Manifold Swirl Control Closed",
        "P1147": "Intake Manifold Swirl Solenoid Circuit Open",
        "P1148": "Intake Manifold Swirl Solenoid Short to Ground",
        "P1149": "Intake Manifold Swirl Solenoid Short to B+",
        "P1151": "Injector Circuit Open Cylinder 1",
        "P1152": "Injector Circuit Open Cylinder 2",
        "P1153": "Injector Circuit Open Cylinder 3",
        "P1154": "Injector Circuit Open Cylinder 4",
        "P1155": "Injector Circuit Open Cylinder 5",
        "P1156": "Injector Circuit Open Cylinder 6",
        "P1159": "Fuel Rail Pressure Regulator Control Circuit",
        "P1166": "A/F Sensor 1 B1 Heater Performance",
        "P1167": "A/F Sensor 1 B2 Heater Performance",
        "P1170": "Front O2 Sensor B1 Stuck",
        "P1171": "Front O2 Sensor B2 Stuck",
        "P1178": "Rear O2 Sensor B1 Stuck",
        "P1179": "Rear O2 Sensor B2 Stuck",
        "P1195": "EGR Boost Sensor Signal Open",
        "P1196": "EGR Boost Sensor Signal Short",
        "P1200": "Injector Circuit Malfunction",
        "P1210": "CVVT System Bank 1",
        "P1211": "CVVT System Bank 2",
        "P1212": "CVVT Oil Control Valve Bank 1",
        "P1213": "CVVT Oil Control Valve Bank 2",
        "P1215": "Ground Fault Common Rail System",
        "P1220": "Fuel Pump Control Circuit",
        "P1222": "Fuel Rail Pressure Sensor",
        "P1224": "Throttle Position Sensor B Performance",
        "P1226": "Injection Pump Fuel Metering Control",
        "P1230": "Fuel Pump Run On",
        "P1233": "Fuel Pump Current Error",
        "P1234": "Fuel Pump Relay Signal",
        "P1250": "Pressure Regulator Control Solenoid Circuit",
        "P1252": "Pressure Regulator Learned Value Error",
        "P1300": "Ignition Timing Adjust",
        "P1307": "Acceleration Sensor Signal",
        "P1308": "Acceleration Sensor Signal",
        "P1310": "Misfire Adaptive Learning Value",
        "P1312": "Engine Speed Sensor",
        "P1320": "Knock Signal Error",
        "P1321": "Knock Sensor 1 Signal High",
        "P1322": "Knock Sensor 2 Signal High",
        "P1323": "Knock Sensor 1 Signal Low",
        "P1324": "Knock Sensor 2 Signal Low",
        "P1330": "Spark Timing Adjust Signal",
        "P1340": "Manufacturing Error",
        "P1345": "Camshaft Position Sensor Circuit",
        "P1386": "Knock Control Processing Fault",
        "P1400": "Manifold Differential Pressure Sensor Circuit",
        "P1401": "EGR Temperature Sensor Circuit",
        "P1402": "Manifold Differential Pressure Sensor Circuit Low",
        "P1403": "Manifold Differential Pressure Sensor Circuit High",
        "P1404": "EGR Valve Position Sensor Circuit Low",
        "P1405": "EGR Valve Position Sensor Circuit High",
        "P1407": "EGR Valve Stuck Closed",
        "P1410": "EGR Differential Pressure Hose Cross Connected",
        "P1443": "EVAP Purge Volume Control Valve",
        "P1449": "EVAP Canister Close Valve",
        "P1450": "Excessive Vacuum EVAP System",
        "P1455": "Fuel Tank Level Sensor",
        "P1460": "Cooling Fan Control Circuit",
        "P1485": "EGR Position Control Solenoid Circuit Low",
        "P1486": "EGR Position Control Solenoid Circuit High",
        "P1487": "EGR Boost Sensor Control Circuit",
        "P1500": "Park/Neutral Switch Signal",
        "P1505": "Idle Air Control Valve Opening Coil Low",
        "P1506": "Idle Air Control Valve Opening Coil High",
        "P1507": "Idle Air Control Valve Closing Coil Low",
        "P1508": "Idle Air Control Valve Closing Coil High",
        "P1510": "Idle Air Control Valve Performance",
        "P1515": "A/C Compressor Signal",
        "P1522": "Immobilizer Signal Error",
        "P1523": "VICS Solenoid Circuit",
        "P1586": "A/T ECM CAN Communication Error",
        "P1587": "TPS A/D Conversion Low",
        "P1588": "TPS A/D Conversion High",
        "P1600": "PCM Battery Backup Circuit",
        "P1602": "Immobilizer System Code Not Programmed",
        "P1605": "CO Adjustment Error",
        "P1606": "Rough Road Sensor Failure",
        "P1608": "PCM Internal Malfunction",
        "P1610": "Immobilizer Communication Error",
        "P1611": "MIL Circuit Malfunction",
        "P1612": "ECM Matching Error",
        "P1614": "MAP Sensor A/D Conversion Error",
        "P1615": "O2 Sensor A/D Conversion Error",
        "P1616": "General Sensor Error",
        "P1617": "Battery Voltage A/D Error",
        "P1618": "TPS A/D Error",
        "P1621": "Alternator FR Signal",
        "P1622": "Generator Normal Error",
        "P1624": "A/C Relay Circuit",
        "P1630": "Battery Voltage Out Of Range",
        "P1632": "Battery Sensor 1 Circuit",
        "P1633": "Battery Sensor 2 Circuit",
        "P1634": "Accelerator Position Sensor 1 Error",
        "P1635": "Accelerator Position Sensor 2 Error",
        "P1636": "Electric Throttle System General Error",
        "P1637": "Electronic Throttle Body Position Error",
        "P1640": "Alternator FR Signal Error",
        "P1650": "Power Steering Pressure Switch",
        "P1652": "Idle Speed Control Actuator",
        "P1655": "ETS Motor Driver Error",
        "P1660": "Power Stage Group A",
        "P1665": "Power Stage Group B",
        "P1670": "Electronic Module Voltage Fault",
        "P1690": "OBD Monitor Not Complete",
        "P1693": "MIL Circuit Open",
        "P1694": "MIL Circuit Short",
        "P1700": "Transmission Range Sensor Circuit",
        "P1705": "Transmission Range Sensor Performance",
        "P1709": "Park/Neutral Switch Performance",
        "P1711": "Transmission Fluid Temp Sensor Error",
        "P1723": "Transmission Speed Sensor Error",
        "P1740": "TCC Solenoid Circuit",
        "P1760": "Pressure Control Solenoid A",
        "P1765": "Timing Solenoid Circuit",
    }
    for code, desc in hyundai.items():
        entries.append(make_entry(code, desc, "Hyundai/Kia"))

    return entries


def main():
    print(f"Lendo arquivo: {INPUT_FILE}")
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        existing = json.load(f)

    original_count = len(existing)
    print(f"DTCs existentes: {original_count}")

    existing_codes = {item["code"] for item in existing}

    oem_dtcs = build_oem_dtcs()
    total_generated = len(oem_dtcs)
    print(f"DTCs OEM gerados: {total_generated}")

    added = 0
    skipped = 0
    by_manufacturer = {}

    for entry in oem_dtcs:
        manufacturer = entry["system"].split(" - ")[-1].replace(" Enhanced", "")
        if entry["code"] not in existing_codes:
            existing.append(entry)
            existing_codes.add(entry["code"])
            added += 1
            by_manufacturer[manufacturer] = by_manufacturer.get(manufacturer, 0) + 1
        else:
            skipped += 1

    existing.sort(key=lambda x: x["code"])

    final_count = len(existing)
    print(f"\nEscrevendo {final_count} DTCs no arquivo...")
    with open(INPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(existing, f, indent=1, ensure_ascii=False)

    print("\n" + "=" * 50)
    print("RESUMO DA EXPANSÃO DE DTCs")
    print("=" * 50)
    print(f"DTCs originais:     {original_count}")
    print(f"DTCs OEM gerados:   {total_generated}")
    print(f"DTCs adicionados:   {added}")
    print(f"DTCs duplicados:    {skipped}")
    print(f"Total final:        {final_count}")
    print(f"\nPor fabricante:")
    for mfr, count in sorted(by_manufacturer.items()):
        print(f"  {mfr:20s}: +{count} códigos")
    print("=" * 50)
    print("Concluído com sucesso!")


if __name__ == "__main__":
    main()
